version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

# \todo Consider reinstating if this feature request is ever implemented:
#  https://github.com/dependabot/dependabot-core/issues/1639
#  - package-ecosystem: gitsubmodule
#    directory: "/"
#    schedule:
#      interval: daily
