name: Draft Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to release
        required: true
        type: string

permissions:
  contents: write

env:
  GH_REPO: ${{ github.repository }}
  GH_TOKEN: ${{ github.token }}

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Create draft release
        run: .github/workflows/release.sh "${TAG_NAME}"
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.event.inputs.tag }}
